import { test, expect } from "@playwright/test";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const fixturePath = path.resolve("test-results/admin-fixture.json");
const support = (action) => execFileSync(path.resolve("../backend/.venv/Scripts/python.exe"), [path.resolve("../backend/tests/admin_support.py"), action, fixturePath], { encoding: "utf8" });
let fixture;
const persist = () => fs.writeFileSync(fixturePath, JSON.stringify(fixture));
test.beforeAll(() => { support("setup"); fixture = JSON.parse(fs.readFileSync(fixturePath)); });
test.afterAll(() => { if (fixture) console.log(support("cleanup")); });

test("complete admin and customer flow on MySQL", async ({ page, request, browser }) => {
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  const credentials = JSON.parse(support("credentials"));
  const categoryName = `Admin category ${fixture.tag}`;
  const foodName = `Admin food ${fixture.tag}`;
  const editedName = `Edited food ${fixture.tag}`;
  const deletedCategoryName = `Delete category ${fixture.tag}`;
  const deletedFoodName = `Delete food ${fixture.tag}`;
  const firstImage = path.resolve("test-results/first.png");
  const replacement = path.resolve("test-results/replacement.webp");
  let headers;
  let food;
  let customer;
  let customerContext;
  const menu = (name) => page.locator(".sidebar").getByRole("link", { name: new RegExp(name) }).click();
  const foodRow = (name) => page.getByRole("row").filter({ has: page.getByRole("cell", { name, exact: true }) });
  const categoryRow = (name) => page.getByRole("row").filter({ has: page.getByRole("cell", { name, exact: true }) });
  const imageLoaded = async (image) => { await expect(image).toBeVisible(); await expect.poll(() => image.evaluate((node) => node.complete && node.naturalWidth > 0)).toBe(true); };
  const captureFood = async (method) => {
    const response = page.waitForResponse((r) => r.url().includes("/api/foods/") && r.request().method() === method && !r.url().includes("/images"));
    await page.getByRole("button", { name: "Save", exact: true }).click();
    const result = await response;
    expect(result.status()).toBe(method === "POST" ? 201 : 200);
    const saved = await result.json();
    await expect(page.getByRole("dialog")).not.toBeVisible();
    return saved;
  };
  const verifyDashboard = async () => {
    const response = await request.get("/api/dashboard/", { headers });
    expect(response.status()).toBe(200);
    const data = await response.json();
    fixture.dashboard = data; persist(); console.log(support("verify-dashboard"));
    for (const [label, value] of [["Total Foods", data.total_foods], ["Total Categories", data.total_categories], ["Total Customers", data.total_customers], ["Total Orders", data.total_orders], ["Pending Orders", data.pending_orders], ["Delivered Orders", data.delivered_orders]]) {
      await expect(page.locator(".stat").filter({ hasText: label }).locator("strong")).toHaveText(String(value));
    }
    await expect(page.locator(".stat").filter({ hasText: "Total Revenue" }).locator("strong")).toHaveText(`Rs. ${Number(data.total_revenue).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`);
    await expect(page.locator(".bar-row")).toHaveCount(data.popular_foods.length);
    for (const item of data.popular_foods) await expect(page.locator(".bar-row").filter({ hasText: item.name })).toContainText(`${item.orders} orders`);
    await expect(page.locator("tbody tr")).toHaveCount(data.recent_orders.length);
    for (const order of data.recent_orders) await expect(page.locator("tbody tr").filter({ hasText: `#${order.id}` })).toContainText(order.status);
  };
  await test.step("Admin Login and anonymous protected routes", async () => {
    for (const route of ["/admin", "/admin/categories", "/admin/foods", "/admin/orders", "/admin/customers"]) {
      await page.goto(route); await expect(page).toHaveURL(/\/login$/);
    }
    expect((await request.get("/api/dashboard/")).status()).toBe(401);
    await page.getByLabel("Email").fill(credentials.email);
    await page.getByLabel("Password").fill("wrong-admin-password");
    await page.getByRole("button", { name: "Login", exact: true }).click();
    await expect(page.getByRole("alert")).toContainText("Invalid email or password");
    await page.getByLabel("Password").fill(credentials.password);
    await page.getByRole("button", { name: "Login", exact: true }).click();
    await expect(page).toHaveURL(/\/admin$/);
    await expect(page.getByRole("heading", { name: "Dashboard", exact: true })).toBeVisible();
    const user = await page.evaluate(() => JSON.parse(localStorage.getItem("foodie_user")));
    headers = { Authorization: `Bearer ${user.access_token}` };
  });
  await test.step("Admin Dashboard matches MySQL", verifyDashboard);
  await test.step("View, add and edit categories", async () => {
    await menu("Categories");
    const list = await (await request.get("/api/categories/", { headers })).json();
    await expect(page.locator("tbody tr")).toHaveCount(list.length);
    await page.getByLabel("Category name").fill("   ");
    await page.getByRole("button", { name: "Add Category", exact: true }).click();
    await expect(page.getByRole("alert")).toContainText("required");
    await page.getByLabel("Category name").fill(categoryName);
    await page.getByLabel("Description", { exact: true }).fill("Initial category description");
    const response = page.waitForResponse((r) => r.url().endsWith("/api/categories/") && r.request().method() === "POST");
    await page.getByRole("button", { name: "Add Category", exact: true }).click();
    const saved = await (await response).json();
    fixture.categories.push(saved.id); persist();
    await expect(categoryRow(categoryName)).toContainText("Initial category description");
    await categoryRow(categoryName).getByRole("button", { name: "Edit", exact: true }).click();
    await page.getByLabel("Description", { exact: true }).fill("Edited category description");
    await page.getByRole("button", { name: "Update Category", exact: true }).click();
    await expect(categoryRow(categoryName)).toContainText("Edited category description");
    await categoryRow(categoryName).getByRole("button", { name: "Edit", exact: true }).click();
    await page.getByRole("button", { name: "Cancel", exact: true }).click();
    await expect(page.getByLabel("Category name")).toHaveValue("");
    expect((await request.post("/api/categories/", { headers, data: { name: categoryName } })).status()).toBe(409);
  });
  await test.step("View Foods, form validation, image preview and Add Food", async () => {
    await menu("Foods");
    const list = await (await request.get("/api/foods/?limit=8", { headers })).json();
    await expect(page.locator("tbody tr")).toHaveCount(list.items.length);
    await page.getByRole("button", { name: "+ Add Food", exact: true }).click();
    await page.getByRole("button", { name: "Cancel", exact: true }).click();
    await expect(page.getByRole("dialog")).not.toBeVisible();
    await page.getByRole("button", { name: "+ Add Food", exact: true }).click();
    await page.getByRole("button", { name: "Save", exact: true }).click();
    await expect(page.getByRole("dialog")).toBeVisible();
    expect(await page.getByLabel("Food Name").evaluate((input) => input.validity.valueMissing)).toBe(true);
    await page.getByLabel("Food Name").fill(foodName);
    await page.getByLabel("Description", { exact: true }).fill("Original food description");
    await page.getByLabel("Price (Rs.)").fill("0");
    expect(await page.getByLabel("Price (Rs.)").evaluate((input) => input.checkValidity())).toBe(false);
    await page.getByLabel("Price (Rs.)").fill("20.50");
    await page.getByLabel("Category", { exact: true }).selectOption(String(fixture.categories[0]));
    await page.getByLabel("Food Image", { exact: true }).setInputFiles({ name: "bad.svg", mimeType: "image/svg+xml", buffer: Buffer.from("<svg/>") });
    await expect(page.getByRole("alert")).toContainText("JPG");
    await page.getByLabel("Food Image", { exact: true }).setInputFiles(firstImage);
    await imageLoaded(page.getByRole("img", { name: "Food image preview", exact: true }));
    await page.screenshot({ path: "test-results/admin-food-form.png" });
    food = await captureFood("POST");
    fixture.foods.push(food.id); fixture.uploads = [food.image_url];
    fixture.expected_food = { id: food.id, name: foodName, description: "Original food description", price: 20.50, category_id: fixture.categories[0], is_available: true, image_url: food.image_url }; persist();
    await expect(foodRow(foodName)).toBeVisible();
    await imageLoaded(foodRow(foodName).getByRole("img", { name: foodName, exact: true }));
    expect((await request.get(food.image_url)).status()).toBe(200);
    console.log(support("verify-food"));
    expect((await request.post("/api/foods/", { headers, data: { name: "Invalid", price: 0, category_id: fixture.categories[0] } })).status()).toBe(422);
    expect((await request.post("/api/foods/", { headers, data: { name: "Invalid", price: 1, category_id: 2147483647 } })).status()).toBe(400);
    expect((await request.post("/api/foods/images", { headers, multipart: { file: { name: "fake.png", mimeType: "image/png", buffer: Buffer.from("not an image") } } })).status()).toBe(422);
  });
  await test.step("Edit Food, keep current image, replace image and availability", async () => {
    await foodRow(foodName).getByRole("button", { name: "Edit", exact: true }).click();
    await imageLoaded(page.getByRole("img", { name: "Food image preview", exact: true }));
    await page.getByLabel("Food Name").fill(editedName);
    await page.getByLabel("Description", { exact: true }).fill("Edited food description");
    await page.getByLabel("Price (Rs.)").fill("22.75");
    const oldImage = food.image_url;
    food = await captureFood("PUT");
    expect(food.image_url).toBe(oldImage);
    await foodRow(editedName).getByRole("button", { name: "Edit", exact: true }).click();
    await page.getByLabel("Food Image", { exact: true }).setInputFiles(replacement);
    await imageLoaded(page.getByRole("img", { name: "Food image preview", exact: true }));
    await page.getByLabel("Available", { exact: true }).uncheck();
    food = await captureFood("PUT");
    expect(food.image_url).not.toBe(oldImage);
    fixture.uploads.push(food.image_url);
    fixture.expected_food = { id: food.id, name: editedName, description: "Edited food description", price: 22.75, category_id: fixture.categories[0], is_available: false, image_url: food.image_url }; persist();
    expect((await request.get(oldImage)).status()).toBe(404);
    expect((await request.get(food.image_url)).status()).toBe(200);
    await expect(foodRow(editedName)).toContainText("Unavailable");
    const visible = await (await request.get(`/api/foods/?available_only=true&category_id=${fixture.categories[0]}`, { headers })).json();
    expect(visible.total).toBe(0);
    console.log(support("verify-food"));
    await foodRow(editedName).getByRole("button", { name: "Edit", exact: true }).click();
    await page.getByLabel("Available", { exact: true }).check();
    food = await captureFood("PUT");
    await expect(foodRow(editedName)).toContainText("Available");
  });
  await test.step("Customer sees uploaded image and places order", async () => {
    customerContext = await browser.newContext();
    customer = await customerContext.newPage();
    customer.on("pageerror", (error) => errors.push(error.message));
    await customer.goto("http://127.0.0.1:15174/register");
    await customer.getByLabel("Full name").fill("Admin Flow Customer");
    await customer.getByLabel("Phone").fill("0770001122");
    await customer.getByLabel("Address", { exact: true }).fill("Integration Street");
    await customer.getByLabel("Email").fill(fixture.email);
    await customer.getByLabel("Password").fill("TestPassword123!");
    await customer.getByRole("button", { name: "Register", exact: true }).click();
    await expect(customer).toHaveURL(/\/login$/);
    await customer.getByLabel("Email").fill(fixture.email);
    await customer.getByLabel("Password").fill("TestPassword123!");
    await customer.getByRole("button", { name: "Login", exact: true }).click();
    await expect(customer).toHaveURL("http://127.0.0.1:15174/");
    await imageLoaded(customer.getByRole("img", { name: editedName, exact: true }));
    await customer.route("**" + food.image_url, (route) => route.abort());
    await customer.reload();
    await expect(customer.getByRole("img", { name: editedName + " — no image", exact: true })).toBeVisible();
    await customer.unroute("**" + food.image_url);
    await customer.reload();
    await imageLoaded(customer.getByRole("img", { name: editedName, exact: true }));
    await customer.getByRole("link", { name: "Foods", exact: true }).click();
    await customer.getByPlaceholder("Search for food...").fill(editedName);
    await customer.getByRole("button", { name: "Search", exact: true }).click();
    await imageLoaded(customer.getByRole("img", { name: editedName, exact: true }));
    await customer.getByRole("button", { name: "Add to Cart", exact: true }).click();
    await customer.getByRole("link", { name: "Cart", exact: true }).click();
    await customer.getByRole("button", { name: `Increase ${editedName}` }).click();
    await customer.getByRole("link", { name: "Checkout", exact: true }).click();
    await customer.getByRole("button", { name: "Place Order", exact: true }).click();
    await expect(customer).toHaveURL(/\/order-confirmation\/\d+$/);
    fixture.order_id = Number(customer.url().split("/").pop()); persist();
    await customer.getByRole("link", { name: "View My Orders", exact: true }).click();
    await expect(customer.locator(".badge")).toHaveText("Pending");
  });
  await test.step("View orders, order details and update status visible to customer", async () => {
    await menu("Dashboard"); await verifyDashboard();
    await menu("Orders");
    const row = page.getByRole("row").filter({ has: page.getByRole("cell", { name: `#${fixture.order_id}`, exact: true }) });
    await expect(row).toContainText(fixture.email);
    await expect(row).toContainText(`${editedName} × 2`);
    await row.getByRole("button", { name: "View Details" }).click();
    const details = page.getByRole("region", { name: `Order ${fixture.order_id} details` });
    await expect(details).toContainText("0770001122");
    await expect(details).toContainText("Integration Street");
    await expect(details).toContainText("2 @ Rs. 22.75 = Rs. 45.50");
    await row.getByRole("button", { name: "Hide", exact: true }).click();
    await page.getByLabel(`Status for order ${fixture.order_id}`).selectOption("Preparing");
    await expect(page.getByText("Order status saved.")).toBeVisible();
    await expect(page.getByLabel(`Status for order ${fixture.order_id}`)).toHaveValue("Preparing");
    await page.getByLabel(`Status for order ${fixture.order_id}`).selectOption("Delivered");
    await expect(page.getByLabel(`Status for order ${fixture.order_id}`)).toHaveValue("Delivered");
    await page.getByLabel("Filter status").selectOption("Pending");
    await expect(row).toHaveCount(0);
    await page.getByLabel("Filter status").selectOption("Delivered");
    await expect(row).toBeVisible();
    await page.getByLabel("Filter status").selectOption("");
    await customer.reload(); await expect(customer.locator(".badge")).toHaveText("Delivered");
    console.log(support("verify-order"));
    await menu("Dashboard"); await verifyDashboard();
  });
  await test.step("View customers and password hidden", async () => {
    await menu("Customers");
    const row = page.getByRole("row").filter({ hasText: fixture.email });
    await expect(row).toContainText("Admin Flow Customer");
    await expect(row).toContainText("0770001122");
    await expect(row).toContainText("Integration Street");
    expect(await row.locator("td").last().innerText()).not.toBe("—");
    const response = await request.get("/api/customers/", { headers });
    expect(response.status()).toBe(200); expect(await response.text()).not.toContain("password");
    expect(await (await request.get(`/api/orders/${fixture.order_id}`, { headers })).text()).not.toContain("password");
    expect(await page.locator("body").innerText()).not.toContain("password_hash");
  });
  await test.step("Customers blocked from every admin route and admin action", async () => {
    const user = await customer.evaluate(() => JSON.parse(localStorage.getItem("foodie_user")));
    const customerHeaders = { Authorization: `Bearer ${user.access_token}` };
    for (const route of ["/admin", "/admin/categories", "/admin/foods", "/admin/orders", "/admin/customers"]) {
      await customer.goto(`http://127.0.0.1:15174${route}`); await expect(customer).toHaveURL(/\/login$/); await expect(customer.getByRole("heading", { name: "Login", exact: true })).toBeVisible();
    }
    for (const route of ["/api/dashboard/", "/api/customers/"]) expect((await request.get(route, { headers: customerHeaders })).status()).toBe(403);
    expect((await request.post("/api/categories/", { headers: customerHeaders, data: { name: "Blocked" } })).status()).toBe(403);
    expect((await request.put(`/api/categories/${fixture.categories[0]}`, { headers: customerHeaders, data: { name: "Blocked" } })).status()).toBe(403);
    expect((await request.delete(`/api/categories/${fixture.categories[0]}`, { headers: customerHeaders })).status()).toBe(403);
    expect((await request.post("/api/foods/", { headers: customerHeaders, data: { name: "Blocked", price: 1, category_id: fixture.categories[0] } })).status()).toBe(403);
    expect((await request.put(`/api/foods/${food.id}`, { headers: customerHeaders, data: { price: 1 } })).status()).toBe(403);
    expect((await request.delete(`/api/foods/${food.id}`, { headers: customerHeaders })).status()).toBe(403);
    expect((await request.post("/api/foods/images", { headers: customerHeaders, multipart: { file: { name: "first.png", mimeType: "image/png", buffer: fs.readFileSync(firstImage) } } })).status()).toBe(403);
    expect((await request.patch(`/api/orders/${fixture.order_id}/status`, { headers: customerHeaders, data: { status: "Cancelled" } })).status()).toBe(403);
    await customerContext.close();
  });
  await test.step("Delete unused food, its image and empty category; preserve order history", async () => {
    expect((await request.delete(`/api/foods/${food.id}`, { headers })).status()).toBe(409);
    await menu("Categories");
    await page.getByLabel("Category name").fill(deletedCategoryName);
    const response = page.waitForResponse((r) => r.url().endsWith("/api/categories/") && r.request().method() === "POST");
    await page.getByRole("button", { name: "Add Category", exact: true }).click();
    const category = await (await response).json(); fixture.categories.push(category.id); fixture.deleted_category = category.id; persist();
    await expect(categoryRow(deletedCategoryName)).toBeVisible();
    await menu("Foods");
    await page.getByRole("button", { name: "+ Add Food", exact: true }).click();
    await page.getByLabel("Food Name").fill(deletedFoodName); await page.getByLabel("Price (Rs.)").fill("15"); await page.getByLabel("Category", { exact: true }).selectOption(String(category.id));
    await page.getByLabel("Food Image", { exact: true }).setInputFiles(firstImage);
    const saved = await captureFood("POST"); fixture.foods.push(saved.id); fixture.deleted_food = saved.id; fixture.deleted_image = saved.image_url; fixture.uploads.push(saved.image_url); persist();
    page.once("dialog", (dialog) => dialog.dismiss());
    await foodRow(deletedFoodName).getByRole("button", { name: "Delete", exact: true }).click();
    await expect(foodRow(deletedFoodName)).toBeVisible();
    page.once("dialog", (dialog) => dialog.accept());
    await foodRow(deletedFoodName).getByRole("button", { name: "Delete", exact: true }).click();
    await expect(foodRow(deletedFoodName)).toHaveCount(0);
    expect((await request.get(saved.image_url)).status()).toBe(404);
    await menu("Categories");
    page.once("dialog", (dialog) => dialog.accept()); await categoryRow(deletedCategoryName).getByRole("button", { name: "Delete", exact: true }).click();
    await expect(categoryRow(deletedCategoryName)).toHaveCount(0);
    console.log(support("verify-delete"));
    page.once("dialog", (dialog) => dialog.accept()); await categoryRow(categoryName).getByRole("button", { name: "Delete", exact: true }).click();
    await expect(page.getByRole("alert")).toContainText("still has foods");
  });
  await test.step("Responsive layout, retryable errors and Admin Logout", async () => {
    await menu("Dashboard");
    for (const [name, endpoint] of [["Categories", "categories/"], ["Foods", "foods/**"], ["Orders", "orders/**"], ["Customers", "customers/"]]) {
      const pattern = "**/api/" + endpoint;
      await page.route(pattern, (route) => route.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ detail: "Temporary test outage" }) }));
      await menu(name);
      await expect(page.getByRole("alert")).toContainText("Temporary test outage");
      await page.unroute(pattern);
      await page.getByRole("button", { name: "Refresh", exact: true }).click();
      await expect(page.locator("tbody tr").first()).toBeVisible();
      await expect(page.getByRole("alert")).toHaveCount(0);
    }
    await page.setViewportSize({ width: 390, height: 844 });
    await menu("Foods");
    await expect(foodRow(editedName)).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.getByRole("button", { name: "+ Add Food", exact: true }).click();
    expect(await page.getByRole("dialog").evaluate((node) => node.getBoundingClientRect().width < window.innerWidth)).toBe(true);
    await page.screenshot({ path: "test-results/admin-food-form-mobile.png" });
    await page.getByRole("button", { name: "Cancel", exact: true }).click();
    await page.route("**/api/dashboard/", (route) => route.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ detail: "Temporary test outage" }) }));
    await menu("Dashboard"); await expect(page.getByRole("alert")).toContainText("Temporary test outage");
    await page.unroute("**/api/dashboard/"); await page.getByRole("button", { name: "Retry", exact: true }).click();
    await expect(page.getByRole("heading", { name: "Dashboard", exact: true })).toBeVisible();
    await page.getByRole("button", { name: "Logout", exact: true }).click();
    await expect(page).toHaveURL(/\/login$/);
    expect(await page.evaluate(() => localStorage.getItem("foodie_user"))).toBeNull();
    await page.goto("/admin"); await expect(page).toHaveURL(/\/login$/);
  });
  expect(errors).toEqual([]);
});
